# Generated by Django 6.0.3 on 2026-05-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='last_checked',
        ),
    ]
